title: Steve's Website
email: steve@stevenpisani.com
description: >- 
  Steve's corner of the Internet. My thoughts, interests, and history.
baseurl: "" 
url: "https://stevenpisani.com" 
twitter_username: stevenpisani
github_username:  stevenpisani

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
